<?php

// Do not edit this file

// Exit if accessed directly
if ( ! defined( 'ABSPATH' ) ) exit;

// Default theme settings values
function generate_posts_and_terms__default_settings_values() {

	$settings                                                       = array();
	
	$w_s_                                                           = 'generate_posts_and_terms__settings_';

	return $settings;
}